# Generated by Django 2.2.1 on 2019-06-28 02:40

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0003_auto_20190618_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appendix',
            name='content_raw',
            field=DjangoUeditor.models.UEditorField(verbose_name='raw content'),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='content_rendered',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='rendered content'),
        ),
        migrations.AlterField(
            model_name='forumavatar',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='uploads/forum/avatars/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_raw',
            field=DjangoUeditor.models.UEditorField(verbose_name='raw content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_rendered',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='rendered content'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content_raw',
            field=DjangoUeditor.models.UEditorField(verbose_name='raw content'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content_rendered',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='rendered content'),
        ),
    ]
